#!/bin/bash

python3.8 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install flask
pip install -r requirements.txt
pip install python-dotenv

set FLASK_APP=./website/app.py
# set FLASK_ENV=development

flask drop_all
flask create_all
flask run