#!/bin/bash

python3.8 -m venv venv
. venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

export FLASK_APP=./website/app.py
export FLASK_ENV=development

flask drop_all
flask create_all
flask run